/* tslint:disable */
/* eslint-disable */
/**
 * AivisSpeech Engine
 * AivisSpeech の音声合成エンジンです。
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AivmManifest } from './AivmManifest';
import {
    AivmManifestFromJSON,
    AivmManifestFromJSONTyped,
    AivmManifestToJSON,
} from './AivmManifest';
import type { LibrarySpeaker } from './LibrarySpeaker';
import {
    LibrarySpeakerFromJSON,
    LibrarySpeakerFromJSONTyped,
    LibrarySpeakerToJSON,
} from './LibrarySpeaker';

/**
 * AIVM (Aivis Voice Model) 仕様に準拠した音声合成モデルのメタデータ情報。
 * 
 * AIVM マニフェストには、音声合成モデルに関連する全てのメタデータが含まれる。
 * speakers フィールド内の話者情報は、VOICEVOX ENGINE との API 互換性のために、
 * AIVM マニフェストを基に Speaker / SpeakerStyle / SpeakerInfo / StyleInfo モデルに変換したもの。
 * @export
 * @interface AivmInfo
 */
export interface AivmInfo {
    /**
     * この音声合成モデルがロードされているかどうか
     * @type {boolean}
     * @memberof AivmInfo
     */
    isLoaded: boolean;
    /**
     * この音声合成モデルの新しいバージョンが AivisHub で公開されているかどうか
     * @type {boolean}
     * @memberof AivmInfo
     */
    isUpdateAvailable: boolean;
    /**
     * AivisHub で公開されておらず、ユーザーがローカルからインストールしたモデルの場合は True (ネットワークエラーなどで AivisHub から情報を取得できなかった場合も True を返す)
     * @type {boolean}
     * @memberof AivmInfo
     */
    isPrivateModel: boolean;
    /**
     * AivisHub がデフォルトインストール対象として指定した音声合成モデルかどうか
     * @type {boolean}
     * @memberof AivmInfo
     */
    isDefaultModel?: boolean;
    /**
     * この音声合成モデルの AivisHub で公開されている最新バージョン (AivisHub で公開されていない場合は AIVM マニフェスト記載のバージョン)
     * @type {string}
     * @memberof AivmInfo
     */
    latestVersion: string;
    /**
     * AIVMX ファイルのインストール先パス
     * @type {string}
     * @memberof AivmInfo
     */
    filePath: string;
    /**
     * AIVMX ファイルのインストールサイズ (バイト単位)
     * @type {number}
     * @memberof AivmInfo
     */
    fileSize: number;
    /**
     * AIVM マニフェスト
     * @type {AivmManifest}
     * @memberof AivmInfo
     */
    manifest: AivmManifest;
    /**
     * 話者情報のリスト (VOICEVOX ENGINE 互換)
     * @type {Array<LibrarySpeaker>}
     * @memberof AivmInfo
     */
    speakers: Array<LibrarySpeaker>;
}

/**
 * Check if a given object implements the AivmInfo interface.
 */
export function instanceOfAivmInfo(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "isLoaded" in value;
    isInstance = isInstance && "isUpdateAvailable" in value;
    isInstance = isInstance && "isPrivateModel" in value;
    isInstance = isInstance && "latestVersion" in value;
    isInstance = isInstance && "filePath" in value;
    isInstance = isInstance && "fileSize" in value;
    isInstance = isInstance && "manifest" in value;
    isInstance = isInstance && "speakers" in value;

    return isInstance;
}

export function AivmInfoFromJSON(json: any): AivmInfo {
    return AivmInfoFromJSONTyped(json, false);
}

export function AivmInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AivmInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'isLoaded': json['is_loaded'],
        'isUpdateAvailable': json['is_update_available'],
        'isPrivateModel': json['is_private_model'],
        'isDefaultModel': !exists(json, 'is_default_model') ? undefined : json['is_default_model'],
        'latestVersion': json['latest_version'],
        'filePath': json['file_path'],
        'fileSize': json['file_size'],
        'manifest': AivmManifestFromJSON(json['manifest']),
        'speakers': ((json['speakers'] as Array<any>).map(LibrarySpeakerFromJSON)),
    };
}

export function AivmInfoToJSON(value?: AivmInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'is_loaded': value.isLoaded,
        'is_update_available': value.isUpdateAvailable,
        'is_private_model': value.isPrivateModel,
        'is_default_model': value.isDefaultModel,
        'latest_version': value.latestVersion,
        'file_path': value.filePath,
        'file_size': value.fileSize,
        'manifest': AivmManifestToJSON(value.manifest),
        'speakers': ((value.speakers as Array<any>).map(LibrarySpeakerToJSON)),
    };
}

